data_transformation:
  drop_minority:
    thresh: 2

model_training:
  rf: 
    # max_features: sqrt
    # max_features: log2
    max_features: null #null is read as None


    n_estimators: 8
    # n_estimators: 16
    # n_estimators: 32
    # n_estimators: 64
    # n_estimators: 128
    # n_estimators: 256


  gb:
    learning_rate: 0.1
    learning_rate: 0.05
    learning_rate: 0.01
    learning_rate: 0.001


    subsample: 0.6
    subsample: 0.7
    subsample: 0.8
    subsample: 0.9


    n_estimators: 8
    n_estimators: 16
    n_estimators: 32
    n_estimators: 64
    n_estimators: 128
    n_estimators: 256

  svr:
    model_name: Support Vector Regression
  lasso:
    model_name: Lasso

