data_transformation:
  drop_minority:
    thresh: 10

model_training:
  rf: 
    model_name: Random Forrest
    max_features:
      - sqrt
      - log2
      - None
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
  gb:
    model_name: Gradient Boost
    learning_rate: 
      - 0.1
      - 0.05
      - 0.01
      - 0.001
    subsample:
      - 0.6
      - 0.7
      - 0.8
      - 0.9
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  svr:
    model_name: Support Vector Regression
  lasso:
    model_name: Lasso

